#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ordereddict
Version  : 1.1
Release  : 40
URL      : http://pypi.debian.net/ordereddict/ordereddict-1.1.tar.gz
Source0  : http://pypi.debian.net/ordereddict/ordereddict-1.1.tar.gz
Summary  : UNKNOWN
Group    : Development/Tools
License  : MIT
Requires: ordereddict-license = %{version}-%{release}
Requires: ordereddict-python = %{version}-%{release}
Requires: ordereddict-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
No detailed description available

%package license
Summary: license components for the ordereddict package.
Group: Default

%description license
license components for the ordereddict package.


%package python
Summary: python components for the ordereddict package.
Group: Default
Requires: ordereddict-python3 = %{version}-%{release}

%description python
python components for the ordereddict package.


%package python3
Summary: python3 components for the ordereddict package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ordereddict package.


%prep
%setup -q -n ordereddict-1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554324200
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ordereddict
cp LICENSE %{buildroot}/usr/share/package-licenses/ordereddict/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ordereddict/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
