#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ordereddict
Version  : 1.1
Release  : 12
URL      : https://pypi.python.org/packages/source/o/ordereddict/ordereddict-1.1.tar.gz
Source0  : https://pypi.python.org/packages/source/o/ordereddict/ordereddict-1.1.tar.gz
Summary  : UNKNOWN
Group    : Development/Tools
License  : MIT
Requires: ordereddict-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
No detailed description available

%package python
Summary: python components for the ordereddict package.
Group: Default

%description python
python components for the ordereddict package.


%prep
%setup -q -n ordereddict-1.1

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
