#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ordereddict
Version  : 1.1
Release  : 46
URL      : http://pypi.debian.net/ordereddict/ordereddict-1.1.tar.gz
Source0  : http://pypi.debian.net/ordereddict/ordereddict-1.1.tar.gz
Summary  : A drop-in substitute for Py2.7's new collections.OrderedDict that works in Python 2.4-2.6.
Group    : Development/Tools
License  : MIT
Requires: ordereddict-license = %{version}-%{release}
Requires: ordereddict-python = %{version}-%{release}
Requires: ordereddict-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Drop-in substitute for Py2.7's new collections.OrderedDict. The recipe has big-oh 
performance that matches regular dictionaries (amortized O(1) 
insertion/deletion/lookup and O(n) iteration/repr/copy/equality_testing).

Originally based on http://code.activestate.com/recipes/576693/

%package license
Summary: license components for the ordereddict package.
Group: Default

%description license
license components for the ordereddict package.


%package python
Summary: python components for the ordereddict package.
Group: Default
Requires: ordereddict-python3 = %{version}-%{release}

%description python
python components for the ordereddict package.


%package python3
Summary: python3 components for the ordereddict package.
Group: Default
Requires: python3-core
Provides: pypi(ordereddict)

%description python3
python3 components for the ordereddict package.


%prep
%setup -q -n ordereddict-1.1
cd %{_builddir}/ordereddict-1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583193169
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ordereddict
cp %{_builddir}/ordereddict-1.1/LICENSE %{buildroot}/usr/share/package-licenses/ordereddict/38abaf3c887f1799769b604e6d1ada4fcb81f8a0
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ordereddict/38abaf3c887f1799769b604e6d1ada4fcb81f8a0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
